### ISSUE TITLE
zstd error out on skippable frames

### ISSUE THREAD

**Issue by scherepanov** [facebook/zstd#904] opened 2017-11-01 17:27 UTC
Hi,
Zstd framing format is compatible with Lz4 for skippable frames (per @Cyan4973 and docs)
lz4 utility is skipping skippable frames, but zstd does not.
I created 48-byte file with one skippable frame:

 hexdump -C /tmp/test.zst
00000000  5e 2a 4d 18 28 00 00 00  00 00 00 00 00 00 00 00  |^*M.(...........|
00000010  00 00 00 00 16 03 01 00  c3 ff 0f 00 03 00 00 00  |................|
00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 e3 ce  |................|
00000030

lz4 handles it:

lz4 -t /tmp/test.zst
/tmp/test.zst        : decoded 0 bytes  

zstd failing:

zstd -t /tmp/test.zst
/tmp/test.zst : Decoding error (36) : Corrupted block detected 

zstd tested on today's version of repo.

Please modify zstd utility to silently skip skippable frames (that is exactly what skippable frames for).
I am creating files with skippable frames that contains transport info, and I want to be able to decompress it using standard tools.

Also, I do have impression that originally zstd was handling skippable frames correctly - means silently skipping htem, like lz4? Am I wrong?

Thank you

**Comment by terrelln** [comment] 2017-11-01 18:12
I've confirmed the problem, I'm looking into it.

**Comment by scherepanov** [comment] 2017-11-01 18:14
Wow, that was quick. Thanks for looking.
I encounter other bug, when large block compressed in one shot gives an error when being decompressed by streaming decompress. Very weird error. I am trying to create test case.

**Comment by terrelln** [comment] 2017-11-01 18:30
I've bisected the bug to PR #836, but I don't know exactly what is going on yet.

**Comment by terrelln** [comment] 2017-11-01 19:23
That PR just exposed a bug that has been around since the beginning. Any skippable frame larger than the block size will be rejected. In the case of just a skippable frame the limit was 1024, and the PR reduced it to 4.

This patch will revert to the previous behavior, so if it worked before it should work with this patch, but I still need to fix the larger problem.

```patch
From 1b4d1b01ecd930e83d8ea263e85622635be53b07 Mon Sep 17 00:00:00 2001
From: Nick Terrell <terrelln@fb.com>
Date: Wed, 1 Nov 2017 12:21:50 -0700
Subject: [PATCH] Revert to previous behavior

---
 lib/decompress/zstd_decompress.c | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/lib/decompress/zstd_decompress.c b/lib/decompress/zstd_decompress.c
index 96fc609..fdb65ef 100644
--- a/lib/decompress/zstd_decompress.c
+++ b/lib/decompress/zstd_decompress.c
@@ -2502,7 +2502,7 @@ size_t ZSTD_decompressStream(ZSTD_DStream* zds, ZSTD_outBuffer* output, ZSTD_inB
             if (zds->fParams.windowSize > zds->maxWindowSize) return ERROR(frameParameter_windowTooLarge);
 
             /* Adapt buffer sizes to frame header instructions */
-            {   size_t const neededInBuffSize = MAX(zds->fParams.blockSizeMax, 4 /* frame checksum */);
+            {   size_t const neededInBuffSize = MAX(zds->fParams.blockSizeMax, 1024 /* frame checksum */);
                 size_t const neededOutBuffSize = ZSTD_decodingBufferSize_min(zds->fParams.windowSize, zds->fParams.frameContentSize);
                 if ((zds->inBuffSize < neededInBuffSize) || (zds->outBuffSize < neededOutBuffSize)) {
                     size_t const bufferSize = neededInBuffSize + neededOutBuffSize;
-- 
2.10.0
```

**Comment by terrelln** [comment] 2017-11-01 20:15
Thanks for reporting the bug @scherepanov! The linked PR should fix the issue, and will be merged once the tests pass. If you have reproduction steps for the other bug you mentioned please open another issue.

**Comment by scherepanov** [comment] 2017-11-01 20:24
Fortunately (or unfortunately) it is my bug :)
It took me to write reproducer to find where I am wrong. Zstd is very mature and bug are scarce.
Thanks for quick fix for skippable frames!

**Closed** 2017-11-01 21:36 UTC
Labels: bug
