### ISSUE TITLE
zstd 1.5.2 still has performace issue

### ISSUE THREAD

**Issue by stevenshiau** [facebook/zstd#3150] opened 2022-06-02 03:16 UTC
I believe zstd 1.5.2 still has the performance issue, as it did in zstd 1.5.1, i.e.,
related to this closed issue: https://github.com/facebook/zstd/issues/2966

The way to reproduce this issue:
1. Create a 2 GB partition on amd64 Debian Linux, say /dev/sda1. I am doing it on a VM here, boot from a Debian Sid live system.
2. dd if=/dev/urandom of=/dev/sda1
3. dpkg -l zstd
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-===============================================
ii  zstd           1.5.2+dfsg-1 amd64        fast lossless compression algorithm -- CLI tool

4. zstd --version
*** zstd command line interface 64-bits v1.5.2, by Yann Collet ***

5. dd if=/dev/sda1 | pv -t | zstdmt -c -3 --rsyncable > /mnt/zstd152.dd
4194304+0 records in
4194304+0 records out
0:01:18
2147483648 bytes (2.1 GB, 2.0 GiB) copied, 78.7535 s, 27.3 MB/s

6. wget http://ftp.us.debian.org/debian/pool/main/libz/libzstd/zstd_1.4.8+dfsg-2.1_amd64.deb

7. dpkg -i zstd_1.4.8+dfsg-2.1_amd64.deb
dpkg: warning: downgrading zstd from 1.5.2+dfsg-1 to 1.4.8+dfsg-2.1
(Reading database ... 44703 files and directories currently installed.)
Preparing to unpack zstd_1.4.8+dfsg-2.1_amd64.deb ...
Unpacking zstd (1.4.8+dfsg-2.1) over (1.5.2+dfsg-1) ...
Setting up zstd (1.4.8+dfsg-2.1) ...

8. zstd --version
*** zstd command line interface 64-bits v1.4.8, by Yann Collet ***

9. dd if=/dev/sda1 | pv -t | zstdmt -c -3 --rsyncable > /mnt/zstd148.dd
4194304+0 records in
4194304+0 records out
0:00:13
2147483648 bytes (2.1 GB, 2.0 GiB) copied, 13.3159 s, 161 MB/s

As you can see, the time difference about using zstd 1.5.2 and 1.4.8 is 78 secs vs. 13 secs. It's 6 times slower...
If you need more info, please let me know.
Thank you very much.

**Comment by yoniko** [comment] 2022-06-02 16:20
The two issues don't seem related to me. https://github.com/facebook/zstd/issues/2966 focused on reusing allocations in cases where inputs are very small and allocation overhead becomes a bottleneck.
On the other hand, in your example you are compressing a 2G partition, so it seems to be a different case.

A simple experiment on my machine didn't reproduce the issue you report here. At the same time, my reproduction wasn't on the same environment and didn't follow exactly the same steps.
It'd be helpful if you could reduce the complexity of this example so we can zero-in on the problem.
Some things that you could try:

1. Re-run zstd v.1.5.2 a second time to make sure this is not a cache / warming up issue.
2. Use a file instead of a partition
3. Instead of piping provide an input path
4. Write out to /dev/null
5. Don't use `rsyncable`
6. Try a lower compression level (use --fast)
7. Compile zstd from source and attempt the same experiment

Answers to these question can help to isolate the issue as well as make it more reproducible for others.

**Comment by stevenshiau** [comment] 2022-06-03 01:31
Thanks for clarifying that, and providing the method to isolate this issue.
I believe we can focus on the "--rsyncable" option. I can always reproduce this performance issue using zstd 1.5.2 as the following.

root@debian:/mnt# dd if=/dev/urandom of=urandom.dd bs=1M count=2000
2000+0 records in
2000+0 records out
2097152000 bytes (2.1 GB, 2.0 GiB) copied, 8.38131 s, 250 MB/s

root@debian:/mnt# zstdmt --version
*** zstd command line interface 64-bits v1.5.2, by Yann Collet ***
root@debian:/mnt# time zstdmt -c --fast urandom.dd > /dev/null

real    0m0.783s
user    0m0.506s
sys     0m1.311s
root@debian:/mnt# time zstdmt -c --fast --rsyncable urandom.dd > /dev/null

real    1m3.668s
user    1m2.417s
sys     0m2.217s
root@debian:/mnt# time zstdmt -c --fast --rsyncable urandom.dd > /dev/null

real    1m3.528s
user    1m0.684s
sys     0m3.805s
root@debian:/mnt# time zstdmt -c --fast urandom.dd > /dev/null

real    0m0.776s
user    0m0.878s
sys     0m0.926s

I also compiled zstd from source, did the same experiment, and got the same result.
If you need me to do more tests, please let me know.
Thank you very much.

**Comment by yoniko** [comment] 2022-06-03 16:37
Thank you, this is helpful, but I'm still unable to reproduce the issue.

Have you tried other zstd versions? It'd be useful to know when the change happened (I can see a couple of related changes in v1.5.1, but would prefer to be sure).

It'd also be helpful if you could:

- Run the same commands with `-vvv` so we can have some more info
- Detail the specs of your system

**Comment by stevenshiau** [comment] 2022-06-04 05:15
Thank you.
Some tests here show that the changes from v1.5.0 to v1.5.1 cause this issue. 
More info is provided as the following.
The environment I am running for this case is on a 4-core CPU/4GB RAM virtual machine of VMWare WS 16.2.3, and OS related info:
-- System Information:
Debian Release: bookworm/sid
  APT prefers unstable
  APT policy: (500, 'unstable')
Architecture: amd64 (x86_64)

Kernel: Linux 5.17.0-3-amd64 (SMP w/4 CPU threads; PREEMPT)
Locale: LANG=en_US.UTF-8, LC_CTYPE=en_US.UTF-8 (charmap=UTF-8), LANGUAGE not set
Shell: /bin/sh linked to /usr/bin/dash
Init: systemd (via /run/systemd/system)

Versions of packages zstd depends on:
ii  libc6       2.33-7
ii  libgcc-s1   12.1.0-2
ii  liblz4-1    1.9.3-2
ii  liblzma5    5.2.5-2.1
ii  libstdc++6  12.1.0-2
ii  zlib1g      1:1.2.11.dfsg-4 

As for different versions, here you are:
**1.5.2**
root@debian:/mnt# time zstdmt -c --fast -vvv urandom.dd > /dev/null
*** zstd command line interface 64-bits v1.5.2, by Yann Collet ***
Note: 4 physical core(s) detected
--zstd=wlog=19,clog=12,hlog=13,slog=1,mml=6,tlen=1,strat=1
--format=.zst --block-size=0 --memory=134217728 --threads=4 --content-size
set nb workers = 4
Using stdout for output
Sparse File Support is automatically disabled on stdout ; try --sparse
urandom.dd: 2097152000 bytes
Decompression will require 524288 B of memory
urandom.dd           : Completed in 2.19 sec  (cpu load : 142%)                   B => 100.00%

real    0m2.198s
user    0m0.017s
sys     0m3.101s
root@debian:/mnt# time zstdmt -c --fast --rsyncable -vvv urandom.dd > /dev/null
*** zstd command line interface 64-bits v1.5.2, by Yann Collet ***
Note: 4 physical core(s) detected
--zstd=wlog=19,clog=12,hlog=13,slog=1,mml=6,tlen=1,strat=1
--format=.zst --block-size=0 --rsyncable --memory=134217728 --threads=4 --content-size
set nb workers = 4
Using stdout for output
Sparse File Support is automatically disabled on stdout ; try --sparse
urandom.dd: 2097152000 bytes
Decompression will require 524288 B of memory
urandom.dd           : Completed in 64.08 sec  (cpu load : 102%)                  B => 100.00%

real    1m4.086s
user    1m2.079s
sys     0m2.988s

**1.5.1**
root@debian:/mnt# time zstdmt -c --fast -vvv urandom.dd > /dev/null
*** zstd command line interface 64-bits v1.5.1, by Yann Collet ***
Note: 4 physical core(s) detected
--zstd=wlog=19,clog=12,hlog=13,slog=1,mml=6,tlen=1,strat=1
--format=.zst --block-size=0 --memory=134217728 --threads=4 --content-size
set nb workers = 4
Using stdout for output
Sparse File Support is automatically disabled on stdout ; try --sparse
urandom.dd: 2097152000 bytes
Decompression will require 524288 B of memory
urandom.dd           : Completed in 0.79 sec  (cpu load : 228%)                   B => 100.00%

real    0m0.796s
user    0m0.015s
sys     0m1.795s
root@debian:/mnt# time zstdmt -c --fast --rsyncable -vvv urandom.dd > /dev/null
*** zstd command line interface 64-bits v1.5.1, by Yann Collet ***
Note: 4 physical core(s) detected
--zstd=wlog=19,clog=12,hlog=13,slog=1,mml=6,tlen=1,strat=1
--format=.zst --block-size=0 --rsyncable --memory=134217728 --threads=4 --content-size
set nb workers = 4
Using stdout for output
Sparse File Support is automatically disabled on stdout ; try --sparse
urandom.dd: 2097152000 bytes
Decompression will require 524288 B of memory
urandom.dd           : Completed in 65.22 sec  (cpu load : 101%)                 B => 100.00%

real    1m5.228s
user    1m4.108s
sys     0m2.079s

**1.5.0**
root@debian:/mnt# time zstdmt -c --fast -vvv urandom.dd > /dev/null
*** zstd command line interface 64-bits v1.5.0, by Yann Collet ***
Note: 4 physical core(s) detected
set nb workers = 4
Using stdout for output
Sparse File Support is automatically disabled on stdout ; try --sparse
urandom.dd: 2097152000 bytes
urandom.dd           : Completed in 0.81 sec  (cpu load : 231%)

real    0m0.808s
user    0m0.028s
sys     0m1.833s
root@debian:/mnt# time zstdmt -c --fast --rsyncable -vvv urandom.dd > /dev/null
*** zstd command line interface 64-bits v1.5.0, by Yann Collet ***
Note: 4 physical core(s) detected
set nb workers = 4
Using stdout for output
Sparse File Support is automatically disabled on stdout ; try --sparse
urandom.dd: 2097152000 bytes
urandom.dd           : Completed in 5.29 sec  (cpu load : 119%)

real    0m5.298s
user    0m4.293s
sys     0m2.034s

**1.4.10**
root@debian:/mnt# time zstdmt -c --fast -vvv urandom.dd > /dev/null
*** zstd command line interface 64-bits v1.4.10, by Yann Collet ***
Note: 4 physical core(s) detected
set nb workers = 4
Using stdout for output
Sparse File Support is automatically disabled on stdout ; try --sparse
urandom.dd: 2097152000 bytes
urandom.dd           : Completed in 1.00 sec  (cpu load : 197%)

real    0m1.005s
user    0m0.183s
sys     0m1.791s
root@debian:/mnt# time zstdmt -c --fast --rsyncable -vvv urandom.dd > /dev/null
*** zstd command line interface 64-bits v1.4.10, by Yann Collet ***
Note: 4 physical core(s) detected
set nb workers = 4
Using stdout for output
Sparse File Support is automatically disabled on stdout ; try --sparse
urandom.dd: 2097152000 bytes
urandom.dd           : Completed in 5.30 sec  (cpu load : 120%)

real    0m5.299s
user    0m4.246s
sys     0m2.096s

**1.4.9**
root@debian:/mnt# time zstdmt -c --fast -vvv urandom.dd > /dev/null
*** zstd command line interface 64-bits v1.4.9, by Yann Collet ***
Note: 4 physical core(s) detected
set nb workers = 4
Using stdout for output
Sparse File Support is automatically disabled on stdout ; try --sparse
urandom.dd: 2097152000 bytes
urandom.dd           : Completed in 0.99 sec  (cpu load : 200%)

real    0m0.996s
user    0m0.045s
sys     0m1.940s
root@debian:/mnt# time zstdmt -c --fast --rsyncable -vvv urandom.dd > /dev/null
*** zstd command line interface 64-bits v1.4.9, by Yann Collet ***
Note: 4 physical core(s) detected
set nb workers = 4
Using stdout for output
Sparse File Support is automatically disabled on stdout ; try --sparse
urandom.dd: 2097152000 bytes
urandom.dd           : Completed in 5.30 sec  (cpu load : 119%)

real    0m5.302s
user    0m3.734s
sys     0m2.579s


**1.4.8**
root@debian:/mnt# time zstdmt -c --fast -vvv urandom.dd > /dev/null
*** zstd command line interface 64-bits v1.4.8, by Yann Collet ***
Note: 4 physical core(s) detected
set nb workers = 4
Using stdout for output
Sparse File Support is automatically disabled on stdout ; try --sparse
urandom.dd: 2097152000 bytes
urandom.dd           : Completed in 0.78 sec  (cpu load : 234%)

real    0m0.781s
user    0m0.045s
sys     0m1.779s
root@debian:/mnt# time zstdmt -c --fast --rsyncable -vvv urandom.dd > /dev/null
*** zstd command line interface 64-bits v1.4.8, by Yann Collet ***
Note: 4 physical core(s) detected
set nb workers = 4
Using stdout for output
Sparse File Support is automatically disabled on stdout ; try --sparse
urandom.dd: 2097152000 bytes
urandom.dd           : Completed in 5.27 sec  (cpu load : 119%)

real    0m5.274s
user    0m3.672s
sys     0m2.610s

**Comment by stevenshiau** [comment] 2022-06-04 07:36
From the tests, I noticed that although the manual of zstd mentions:
--rsyncable : zstd will periodically synchronize the compression state to make the compressed file more rsync-friendly. There is  a  negligible impact  to  compression ratio, and the faster compression levels will see a small compression speed hit.

the speed for compression can be a big difference with or without "--rsyncable"... Hence we temporarily removed "--rsyncable" when using zstdmt in our project.
Thank you very much.

**Comment by terrelln** [comment] 2022-06-06 18:45
Ah, I figured it out!

The issue is caused by https://github.com/facebook/zstd/commit/9d9e2ed00baa70652c1b8255b3ff16057a702f2e. It added this assert:

https://github.com/facebook/zstd/blob/9f346dbe45111a9704c02bbc58360982a3f62069/lib/compress/zstdmt_compress.c#L1766

When zstd is compiled with asserts, the CPU time of your command is 84 seconds. Without asserts it is 7 seconds.

We can remove this assert for now, but I will also open an issue on Debian and ask why they are compiling with asserts enabled.

**Comment by terrelln** [comment] 2022-06-06 19:00
Also, we should be able to significantly speed up rsyncable mode by using the new gear rolling hash that we're using in LDM.

**Comment by yoniko** [comment] 2022-06-06 19:08
@terrelln - thank you for investigating and mitigating!
I've approved the PR https://github.com/facebook/zstd/pull/3154.

@stevenshiau - can you compile https://github.com/facebook/zstd/pull/3154 and check that it mitigates the issue for you?

**Comment by terrelln** [comment] 2022-06-06 19:08
> I also compiled zstd from source, did the same experiment, and got the same result.

@stevenshiau did you enable asserts when you compiled from source.

**Comment by stati64** [comment] 2022-06-06 20:13
We fell into this 50% slower by default trap also.

**Comment by terrelln** [comment] 2022-06-06 20:50
@stati64 what do you mean?

**Comment by stevenshiau** [comment] 2022-06-07 14:21
> @stevenshiau - can you compile #3154 and check that it mitigates the issue for you?

Yes, I have compiled $3154 and confirmed it mitigates the issue:
root@debian:/mnt# time zstdmt -c --fast -vvv urandom.dd > /dev/null
*** zstd command line interface 64-bits v1.5.2, by Yann Collet ***
Note: 4 physical core(s) detected
--zstd=wlog=19,clog=12,hlog=13,slog=1,mml=6,tlen=1,strat=1
--format=.zst --no-sparse --block-size=0 --memory=134217728 --threads=4 --content-size
set nb workers = 4
Using stdout for output
urandom.dd: 2097152000 bytes
Decompression will require 524288 B of memory
urandom.dd           : Completed in 0.87 sec  (cpu load : 305%)                00.00%

real    0m0.874s
user    0m0.936s
sys     0m1.721s

root@debian:/mnt# time zstdmt -c --fast --rsyncable -vvv urandom.dd > /dev/null
*** zstd command line interface 64-bits v1.5.2, by Yann Collet ***
Note: 4 physical core(s) detected
--zstd=wlog=19,clog=12,hlog=13,slog=1,mml=6,tlen=1,strat=1
--format=.zst --no-sparse --block-size=0 --rsyncable --memory=134217728 --threads=4 --content-size
set nb workers = 4
Using stdout for output
urandom.dd: 2097152000 bytes
Decompression will require 524288 B of memory
urandom.dd           : Completed in 5.31 sec  (cpu load : 152%)                00.00%

real    0m5.310s
user    0m3.108s
sys     0m4.964s

> @stevenshiau did you enable asserts when you compiled from source.

I believe so, since I just reused the rules from Debian to compile and package it as a deb, then install it in my testing environment.
Thank you very much for addressing this issue.

**Comment by yoniko** [comment] 2022-06-09 16:31
Closing the issue, please reopen if there's any followup.

**Closed as completed by yoniko** 2022-06-09 16:31 UTC

**Comment by devZer0** [comment] 2023-03-22 17:11
@stevenshiau ,i would also call this performance issue, or at least documentation issue

see my findings at https://github.com/facebook/zstd/issues/3567
