### ISSUE TITLE
How can I compress a directory?

### ISSUE THREAD

**Issue by g666gle** [facebook/zstd#1526] opened 2019-02-16 19:08 UTC
I need to compress a directory using zstd and I saw somewhere that there was a work around. Any ideas?

**Comment by terrelln** [comment] 2019-02-16 19:18
`zstd` is a compressor, not an archiver. You can compress each file in a directory individually using `zstd -r directory/`. If you want to compress the whole directory you should use `tar` or `libarchive`.

For example, you can compress a directory with `tar` using zstd with the command line:

```
tar --zstd -cf directory.tar.zst directory/
```

If you have an older version of `tar` without native zstd support you can use:

```
tar --use-compress-program zstd -cf directory.tar.zst directory/
```

**Comment by g666gle** [comment] 2019-02-16 21:38
How would you decompress the "dir_name.tar.zst" directory?

**Comment by terrelln** [comment] 2019-02-16 22:43
tar --zstd -xf directory.tar.zst

You can google how to use tar for more detailed instructions.

**Comment by terrelln** [comment] 2019-02-19 22:40
I'm going to close this issue, feel free to reopen if you have further questions.

**Closed by terrelln** 2019-02-19 22:40 UTC

**Comment by whitman-colm** [comment] 2019-03-26 16:10
How could I set the compression level on it? I know there's a `GZIP` variable but I don't know if it applies here. I tried the `--options` suggested by jsonn in [libarchive/#957](https://github.com/libarchive/libarchive/issues/957#issuecomment-334576073) but it says `options` isn't a valid argument. I'm using tar v1.32 if that helps. Thanks!

**Comment by terrelln** [comment] 2019-03-26 17:28
Since zstd-1.3.8 we default to the compression level set in the ZSTD_CLEVEL environment variable if set

**Comment by sergeevabc** [comment] 2019-04-10 01:43
```
$ tar --version
tar (GNU tar) 1.31

$ tar --zstd -cf logs.tar.zst logs/
tar (child): zstd: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
/Unix/tar: directory: Cannot write: Broken pipe
/Unix/tar: Child returned status 2
/Unix/tar: Error is not recoverable: exiting now
```
:(

**Comment by terrelln** [comment] 2019-04-10 02:00
I suspect that `tar` can't find `zstd` in your path. Where did you install zstd? Does `tar --use-compress-program zstd` also fail?

**Comment by sergeevabc** [comment] 2019-04-10 09:45
@terrelln, required files `tar.exe` and `zstd.exe` are placed and launched in the same folder.
`tar --use-compress-program zstd` also fails with the same aforementioned error.
The only successful workaround so far is `tar cf - logs | zstd > logs.tar.zst`.
I have packed the following tree in [test.zip][1] for you to replicate.
```
C:\Test                      
|-- Logs                     
|   |-- Tor                  
|   |   |-- freenode.Tor.log 
|   |   `-- server.Tor.log       
|   |-- freenode.log         
|   `-- server.log           
|-- msys-2.0.dll             
|-- msys-iconv-2.dll         
|-- msys-intl-8.dll          
|-- tar.exe                  
`-- zstd.exe

$ sha1sum test.zip
6de8be4fe94f6b95a1fe6832926bb6f30fae4f71 *test.zip                 
```
[1]: https://linx.li/test.zip

**Comment by terrelln** [comment] 2019-04-10 18:23
I believe that this is a problem with your setup. I didn't even know that `tar` worked on Windows.

I suspect that the `$PATH` that tar gets doesn't align with Windows path, so it can't find `zstd`.

Does it work if you provide the full path the the zstd executable (with or without `.exe`), or with `zstd.exe`?

In either way, this isn't a bug in zstd, and isn't a problem with tar on Unix systems, but maybe a deficiency of `tar` on Windows, if they officially support that.

**Comment by sergeevabc** [comment] 2019-04-10 20:06
@terrelln, have you tried to reproduce the case with the package I provided?

**Comment by terrelln** [comment] 2019-04-10 21:37
Sadly, I don't have a Windows machine, so I won't be able to reproduce it. But, I'm confident it is a problem related to tar on Windows, not specific to zstd, so I'm not the right person to fix it.

**Comment by sergeevabc** [comment] 2019-04-12 22:31
Workaround to create: 
`7z.exe -ttar a dummy "c:\Test\Logs" -so | zstd.exe --long -o logs.tar.zst`

Extracting as usual:
`tar.exe -xf logs.tar.zst`

**Comment by alibitek** [comment] 2020-07-22 15:06
When doing `tar --zstd -cf directory.tar.zst directory/` is there an environment variable to specify the the number of compression threads? 
Aka what this option does: `-T#    : spawns # compression threads (default: 1, 0==# cores) `

**Comment by Cyan4973** [comment] 2020-07-22 16:48
Nope.
This feature has already been requested, and is currently part of our backlog.

**Comment by c02y** [comment] 2020-09-05 04:09
Hi there, how to use zstd options with tar to compress a directory into .tar.zst?

I'm currently the following command to compress dir directory into dir.tar.zst
```
tar cvfa dir.tar.zst dir
```

But I want to add some options of zstd such as "-c -T0 -18 - " to the tar command line, how can I do that?

**Comment by jboero** [comment] 2020-11-07 09:50
I manage my way around it using `pzstd` instead of `zstd`:

```
tar --use-compress-program pzstd -cf directory.tar.zstd directory/
```
extract:
```
time tar --use-compress-program pzstd -xf directory.tar.zstd
```

**Comment by Cyan4973** [comment] 2020-11-07 16:48
Next release will have `ZSTD_NBTHREADS` for this purpose :
https://github.com/facebook/zstd/blob/dev/programs/README.md#passing-parameters-through-environment-variables

**Comment by oshanz** [comment] 2021-09-29 12:20
`tar -c -I 'zstd -19 -T0' -f directory.tar.zst directory/`

**Comment by pratikbin** [comment] 2021-10-15 12:55
> I manage my way around it using `pzstd` instead of `zstd`. Much faster and you can control parallel threads via pzstd params or just use one for each core by default.
> 
> ```
> tar --use-compress-program pzstd -cf directory.tar.zstd directory/
> ```
> 
> extract:
> 
> ```
> tar --use-compress-program pzstd -xf directory.tar.zstd
> ```

You mean you used `PZSTD_NUM_THREADS` ?

**Comment by terrelln** [comment] 2021-10-15 20:55
> You mean you used PZSTD_NUM_THREADS ?

By default `PZSTD_NUM_THREADS` is undefined and unused, so the default number of threads is `std::thread::hardware_concurrency()`. See:

https://github.com/facebook/zstd/blob/12c045f74d922dc934c168f6e1581d72df983388/contrib/pzstd/Options.cpp#L25-L31

**Comment by SjorsO** [comment] 2024-07-05 10:36
> `tar -c -I 'zstd -19 -T0' -f directory.tar.zst directory/`

This works on Linux but not on MacOS, the following command works on both:

```sh
tar --use-compress-program "zstd -T0 -3" -cf "output.tar.zst" "input-directory/"
```

and for reference, extracting the archive:

```sh
tar --use-compress-program "zstd -d" -xf "archive.tar.zst"
```
