### ISSUE TITLE
build error with contrib part expected unqualified-id before '=' token

### ISSUE THREAD

**Issue by mckaygerhard** [facebook/zstd#2811] opened 2021-09-29 19:43 UTC
**Describe the bug**
it fail to buil in contrib

**To Reproduce**
1. Download the source, i used 1.3, it fails with 1.4
2. just compile

**Expected behavior**
build

**build log of error**
```
[  138s] 	make -j1 pzstd
[  138s] make[2]: Entering directory `/usr/src/packages/BUILD/contrib/pzstd'
[  138s] g++ -MMD -MP -MF main.Td  -D_FORTIFY_SOURCE=2 -I../../lib -I../../lib/common -I../../programs -I. -O3 -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fomit-frame-pointer -march=i686 -mtune=pentium-mmx -mmmx -fexcess-precision=fast   -std=c++11 -c main.cpp  -o main.o
[  138s] In file included from utils/Buffer.h:11:0,
[  138s]                  from Pzstd.h:14,
[  138s]                  from main.cpp:11:
[  138s] ./utils/Range.h:86:32: error: expected ';' at end of member declaration
[  138s] ./utils/Range.h:86:36: error: expected unqualified-id before '=' token
[  138s] ./utils/Range.h:87:27: error: expected ';' at end of member declaration
[  138s] ./utils/Range.h:87:31: error: expected unqualified-id before '=' token
[  138s] In file included from Pzstd.h:14:0,
[  138s]                  from main.cpp:11:
[  138s] utils/Buffer.h:48:29: error: expected ';' at end of member declaration
[  138s] utils/Buffer.h:48:33: error: expected unqualified-id before '=' token
[  138s] make[2]: *** [main.o] Error 1
[  138s] make[2]: Leaving directory `/usr/src/packages/BUILD/contrib/pzstd'
```

**SERVER (i do not use desktop):**
 - OS: Debian
 - Version 9
 - Compiler gcc 5
 - Flags  `-ftree-vectorize -fomit-frame-pointer -march=i686 -mtune=pentium-mmx -mmmx -fexcess-precision=fast`
 - Other relevant hardware specs Pentium4
 - Build system Makefile

**Comment by terrelln** [comment] 2021-11-23 23:38
Pzstd requires building with C++11. So you can fix this by adding the flag `-std=c++11`.

**Comment by mckaygerhard** [comment] 2021-11-29 18:29
> -std=c++11

it seems does not work:

```
[  168s] g++ -MMD -MP -MF main.Td  -D_FORTIFY_SOURCE=2 -I../../lib -I../../lib/common -I../../programs -I. -O3 -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fomit-frame-pointer -march=i586 -mtune=generic -mmmx -fexcess-precision=fast  -Wall -std=c++11  -std=c++11 -c main.cpp  -o main.o
[  169s] In file included from utils/Buffer.h:11:0,
[  169s]                  from Pzstd.h:14,
[  169s]                  from main.cpp:11:
[  169s] ./utils/Range.h:86:32: error: expected ';' at end of member declaration
[  169s] ./utils/Range.h:86:36: error: expected unqualified-id before '=' token
[  169s] ./utils/Range.h:87:27: error: expected ';' at end of member declaration
[  169s] ./utils/Range.h:87:31: error: expected unqualified-id before '=' token
[  169s] In file included from Pzstd.h:14:0,
[  169s]                  from main.cpp:11:
[  169s] utils/Buffer.h:48:29: error: expected ';' at end of member declaration
[  169s] utils/Buffer.h:48:33: error: expected unqualified-id before '=' token
[  169s] make[2]: *** [main.o] Error 1
[  169s] make[2]: Leaving directory `/usr/src/packages/BUILD/contrib/pzstd'
```

**Comment by terrelln** [comment] 2021-12-01 18:04
I think PR #2889 should fix this issue, which is merged into the latest dev branch.

**Comment by terrelln** [comment] 2021-12-01 19:41
Please reopen if the issue isn't fixed.

**Closed as completed by terrelln** 2021-12-01 19:41 UTC
Labels: release-blocking

**Comment by mckaygerhard** [comment] 2021-12-02 16:29
> Please reopen if the issue isn't fixed.

nmany thanks.. ! puff i will test and report feddback

**Comment by mckaygerhard** [comment] 2021-12-03 13:39
good! inclusive it works and compiles in my backported debian wheezy! many many thanks @terrelln
