### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by icebluey** [facebook/zstd#1166] opened 2018-06-06 13:00 UTC
gcc version 7.3.0 (GCC)

I ran 'make all PREFIX=/usr', but got error.
==============================================================
make[1]: Leaving directory '/tmp/build-zstd/zstd/programs'
make -C tests all
make[1]: Entering directory '/tmp/build-zstd/zstd/tests'
cc -I/opt/openssl/include -I../lib -I../lib/common -I../lib/compress -I../lib/dictBuilder -I../lib/deprecated -I../programs -DZSTD_MULTITHREAD -I/opt/openssl/include -Wall -Wextra -Wcast-qual -Wcast-align -Wshadow -Wstrict-aliasing=1 -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wundef -Wformat-security -Wvla -Wformat=2 -Winit-self -Wfloat-equal -Wwrite-strings -Wredundant-decls   -L/opt/openssl/lib -pthread ../programs/datagen.c fullbench.c ../lib/decompress/huf_decompress.c ../lib/decompress/zstd_decompress.c ../lib/common/entropy_common.c ../lib/common/pool.c ../lib/common/error_private.c ../lib/common/xxhash.c ../lib/common/fse_decompress.c ../lib/common/threading.c ../lib/common/zstd_common.c ../lib/compress/zstd_double_fast.c ../lib/compress/zstd_lazy.c ../lib/compress/zstd_fast.c ../lib/compress/zstd_ldm.c ../lib/compress/huf_compress.c ../lib/compress/zstdmt_compress.c ../lib/compress/zstd_compress.c ../lib/compress/fse_compress.c ../lib/compress/zstd_opt.c -o fullbench
mv -f Pzstd.Td Pzstd.d
g++ -MMD -MP -MF SkippableFrame.Td  -I/opt/openssl/include -I../../lib -I../../lib/common -I../../programs -I. -DNDEBUG -O3 -Wall -Wextra -pedantic  -std=c++11 -c SkippableFrame.cpp  -o SkippableFrame.o
mv -f SkippableFrame.Td SkippableFrame.d
g++ main.o Options.o Pzstd.o SkippableFrame.o ../../lib/libzstd.a           -L/opt/openssl/lib   -pthread -o pzstd
make[1]: Leaving directory '/tmp/build-zstd/zstd/contrib/pzstd'
make -C contrib/seekable_format/examples all
make[1]: Entering directory '/tmp/build-zstd/zstd/contrib/seekable_format/examples'
cc -I/opt/openssl/include -I../ -I../../../lib -I../../../lib/common -I/opt/openssl/include -g seekable_compression.c ../zstdseek_compress.c ../zstdseek_decompress.c -L/opt/openssl/lib ../../../lib/libzstd.a -o seekable_compression
../zstdseek_decompress.c:200:5: error: conflicting types for ‘ZSTD_seekable_offsetToFrameIndex’
 U32 ZSTD_seekable_offsetToFrameIndex(ZSTD_seekable* const zs, U64 pos)
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../zstdseek_decompress.c:68:0:
../zstd_seekable.h:168:22: note: previous declaration of ‘ZSTD_seekable_offsetToFrameIndex’ was here
 ZSTDLIB_API unsigned ZSTD_seekable_offsetToFrameIndex(ZSTD_seekable* const zs, unsigned long long offset);
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../zstdseek_decompress.c:225:5: error: conflicting types for ‘ZSTD_seekable_getFrameCompressedOffset’
 U64 ZSTD_seekable_getFrameCompressedOffset(ZSTD_seekable* const zs, U32 frameIndex)
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../zstdseek_decompress.c:68:0:
../zstd_seekable.h:164:32: note: previous declaration of ‘ZSTD_seekable_getFrameCompressedOffset’ was here
 ZSTDLIB_API unsigned long long ZSTD_seekable_getFrameCompressedOffset(ZSTD_seekable* const zs, unsigned frameIndex);
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../zstdseek_decompress.c:231:5: error: conflicting types for ‘ZSTD_seekable_getFrameDecompressedOffset’
 U64 ZSTD_seekable_getFrameDecompressedOffset(ZSTD_seekable* const zs, U32 frameIndex)
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../zstdseek_decompress.c:68:0:
../zstd_seekable.h:165:32: note: previous declaration of ‘ZSTD_seekable_getFrameDecompressedOffset’ was here
 ZSTDLIB_API unsigned long long ZSTD_seekable_getFrameDecompressedOffset(ZSTD_seekable* const zs, unsigned frameIndex);
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../zstdseek_decompress.c: In function ‘ZSTD_seekable_initBuff’:
../zstdseek_decompress.c:349:45: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
                                             &ZSTD_seekable_seek_buff};
                                             ^
../zstdseek_decompress.c:349:45: note: (near initialization for ‘srcFile.seek’)
../zstdseek_decompress.c: In function ‘ZSTD_seekable_initFile’:
../zstdseek_decompress.c:356:41: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
                                         &ZSTD_seekable_seek_FILE};
                                         ^
../zstdseek_decompress.c:356:41: note: (near initialization for ‘srcFile.seek’)
../zstdseek_decompress.c: At top level:
../zstdseek_decompress.c:375:8: error: conflicting types for ‘ZSTD_seekable_decompress’
 size_t ZSTD_seekable_decompress(ZSTD_seekable* zs, void* dst, size_t len, U64 offset)
        ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../zstdseek_decompress.c:68:0:
../zstd_seekable.h:158:20: note: previous declaration of ‘ZSTD_seekable_decompress’ was here
 ZSTDLIB_API size_t ZSTD_seekable_decompress(ZSTD_seekable* zs, void* dst, size_t dstSize, unsigned long long offset);
                    ^~~~~~~~~~~~~~~~~~~~~~~~
Makefile:27: recipe for target 'seekable_compression' failed
make[1]: *** [seekable_compression] Error 1
make[1]: Leaving directory '/tmp/build-zstd/zstd/contrib/seekable_format/examples'
Makefile:97: recipe for target 'contrib' failed
make: *** [contrib] Error 2
make: *** Waiting for unfinished jobs....

==============================================================

**Comment by Cyan4973** [comment] 2018-06-06 18:16
Indeed,
the issue seems to be related
to the `contrib/seekable_format` project.

For some reason, your compiler seems to interpret `U64` and `unsigned long long` differently, resulting in a type error during link stage.

This can be fixed.
I'm just surprised we never generated this issue within our tests, even with are also using gcc version 7.3.0.
Maybe there is something more into your configuration that we could use to reproduce the issue.

**Comment by terrelln** [comment] 2018-06-06 18:23
I've often seen this problem on OS X trying to call `std::min()` on a `size_t` and a `uint64_t`, which fails on OS X even though they are both 8 bytes. One is `unsigned long` and one is `unsigned long long`. We removed our OS X travis test because of the queue times, but I suspect that it would flag the issue.

**Comment by Cyan4973** [comment] 2018-06-06 18:53
Well, I'm currently compiling on OS-X, using `gcc-7`,
and nonetheless, I'm unable to reproduce the issue ...

**Comment by Cyan4973** [comment] 2018-06-06 19:02
_update_ : could reproduce it on an Ubuntu VM, using gcc 5.4.0.

I'm surprised it did not show up in any of our tests.
Circle CI is supposed to test `make all` on a Linux VM too, so it should feature the same behavior ?
The only meaningful difference I could spot is that Circle CI uses gcc 4.8.4.

**Comment by Cyan4973** [comment] 2018-06-06 21:41
fixed in `dev` branch

**Closed** 2018-06-06 21:41 UTC
