### ISSUE TITLE
Symbol not found in shared lib, but present in static lib

### ISSUE THREAD

**Issue by sgiannoulis** [facebook/zstd#2605] opened 2021-05-03 22:58 UTC
**Describe the bug**
Hi all, 
when building ZSTD for use in OpenR i came upon a very strange bug. As ZSTD builds both shared (.so) and static libs (.a), when trying to link openR and its CLI companion Breeze, the shared lib search for the specified symbol would complain it cannot find a symbol, so execution of Breeze would fail. 

ImportError: /usr/local/lib/libfolly.so: undefined symbol: ZSTD_CCtxParams_setParameter

The Folly lib library was built using the shared libzstd.so and the symbol was indeed not found there. It was only found in the .a file.
root:/usr# find ./  -name \*.a -exec bash -c "nm --defined-only {} 2>/dev/null | grep ZSTD_CCtxParams_setParameter && echo {}" \;
0000000000003890 T ZSTD_CCtxParams_setParameter
./local/lib/libzstd.a

How is it possible that the libzstd.so and libzstd.a are not offering the same symbols ? 

**To Reproduce**
Build ZSTD with shared libs on. Build Folly using libzstd.so during linking. Try to execute Breeze when all other deps are installed. Breeze is crushing, coplaining about not finding the ZSTD symbol mentioned above. When removing the libzstd.so file and force folly to link against the libzstd.a file, Breeze works as it can now find the needed symbol. 

**Expected behavior**
Linking against the shared and static lib should be same as far as symbols exposed and functionality. 

**Desktop (please complete the following information):**
 - OS: Debian 
 - Version [10]
 - Compiler [gcc]
 - Other relevant hardware specs [aarch64 architecture]
 - Build system [Cmake-make]

**Comment by Cyan4973** [comment] 2021-05-04 02:19
There are a few things worth developing : 

### Dynamic vs Static Library : Symbol Lists

The static library, by design, make accessible _any_ symbol designed to be visible outside of its own unit.
This is a gigantic list. Most of these symbols are by the way purely internal, and should never be accessed by outside client.

The dynamic library, in contrast, only exposes a selected list of symbols, defined (primarily) in `zstd.h`.
Internal symbols do not appear in this list.
Software using `zstd` API should only use symbols from the public list.

### Stable vs Experimental API

Now, it happens that `ZSTD_CCtxParams_setParameter()` is part of the public list of symbols. So it should be accessible.
But there is a twist.

The `zstd` API is divided into 2 sections,
one that is "stable", where symbols are guaranteed to be present starting from a published version onto the future.

Another list is said "experimental". These are symbols which may still change, or even disappear, in future versions.
Their usage should be tied to a specific version of the library, with no expectation of upward / downward compatibility.
Generally speaking, it is not recommended to use such symbols in combination with dynamic library, which version is unknown by the developer, and could be anything, only discovered at run time.
That's why there is a macro `ZSTD_STATIC_LINKING_ONLY` : it's only reasonable to use these symbols in combination with static library, which version can be controlled by the developper at compilation time.

`ZSTD_CCtxParams_setParameter()` is part of this second list.

### Summary

This symbol should not be used in combination with the dynamic library, 
as it may result in linking error, depending on the specific version of the library present at runtime on the deployed system.

The following options are possible : 
- do not link to the dynamic library, only use a bundled static library
- do not use `ZSTD_CCtxParams_setParameter()`
- only use `ZSTD_CCtxParams_setParameter()` when tied to a specific version of the library

The last 2 options are typically more difficult, as it requires access to the source code, and an ability to refactor it in a way which makes sense. The option 3 is generally not used, since a backup solution must nonetheless exist for other versions of the library, so one might as well stick with it, making it option 2.

Long term, if you believe this experimental API could be useful enough to be transferred into stable,
you can issue a request for promotion into stable.
Note though that it's a slow process, as the maintenance team must carefully balance the perceived benefit with increased maintenance load and more difficulties evolving the code, as each new stable capability lock the feature list and library behavior into something more and more rigid.
Such a request could be candidate for `v1.6.0` at best.

**Comment by sgiannoulis** [comment] 2021-05-04 11:18
Thanks for the explanation @Cyan4973 , care to point where i can find the status for the experimental API on each release so i can maybe switch to a release that the symbol is present in both .so and .a files ? I am currently using 1.4.8. 
Since the projects i am linking zstd against are fb-folly and then fb-openr, i really wouldnt want to go and refactor their API usage of zstd. I will probably just stick on using the static zstd library and not the dynamic one.

**Comment by Cyan4973** [comment] 2021-05-04 15:41
We don't do a great job at tracking version numbers for experimental entry points.
I think the main idea is that such API should be used in combination with a _specific_ version number, not "across many versions starting with this number", since they may (and eventually will) change in some future versions.

Anyway, for `ZSTD_CCtxParams_setParameter()` specifically, this entry point has been present in experimental API since `v1.4.0+`. So far, it has not changed yet.

**Comment by sgiannoulis** [comment] 2021-05-04 16:09
Then i am confused. I am using specifically 1.4.8 version, haven't moved out of it, nor planning to. How do you explain that i can find the symbol on the .a and not on the .so of specifically the 1.4.8 zstd base source code? I am compiling zstd myself and installing the shared and static lib in the system folders. So no way i am using a different version of zstd other than 1.4.8 !

**Comment by Cyan4973** [comment] 2021-05-04 16:14
That I can't explain.
This symbol is [definitely present in `v1.4.8`](https://github.com/facebook/zstd/blob/v1.4.8/lib/zstd.h#L1845) .

Being an experimental symbols, its declaration is hidden behind the build macro `ZSTD_STATIC_LINKING_ONLY`.
But that requirement is the same for both static and dynamic libraries.

**Comment by terrelln** [comment] 2021-05-05 19:47
That symbol is definitely present in the `v1.4.8` shared library.

Maybe your build is picking up a different version of zstd? Maybe and older `libzstd.so` is installed globally on your system?

**Comment by sgiannoulis** [comment] 2021-05-05 19:50
@terrelln Thanks for the response. Unfortunately no, i double checked when cmake was configuring folly and openR build system, the they were picking the correct libzstd.so file, installed in /usr/local/lib from building zstd 1.4.8. 
Could it be that by design, the makefile of zstd does not build the experimental API in the shared .so libs ? 
If you see my initial post, i checked also if the symbol was present in the libzstd.so and it wasnt there.

**Comment by terrelln** [comment] 2021-05-07 05:05
> Could it be that by design, the makefile of zstd does not build the experimental API in the shared .so libs ?

No, zstd currently exposes all public symbols in `libzstd.so`, including experimental symbols.

I don't know how that symbol wouldn't be present. It is present when I build `libzstd.so` on `v1.4.8` with both `make` and `cmake`. Can you paste the output of `nm` for both the shared and static libaries for me? Maybe that will help get to the bottom of it.

**Comment by sgiannoulis** [comment] 2021-05-07 09:49
Double-checked my libs first:

debian@sr-8040:~$ find /usr/ -name libzstd*
/usr/local/lib/libzstd.so.OLD
/usr/local/lib/libzstd.so.1.4.8
/usr/local/lib/libzstd.so.1
/usr/local/lib/libzstd.a
/usr/local/lib/pkgconfig/libzstd.pc
/usr/lib/aarch64-linux-gnu/libzstd.so.1.3.8
/usr/lib/aarch64-linux-gnu/libzstd.so.1
/usr/share/doc/libzstd1

I double checked all libraries in the ld path. Seems there was also a 1.3.8 libzstd1-dev installed from debian in the linux version typical path. 
So double checked again if symbol is present in any of them:
 debian@sr-8040:~$ find /usr/ -name libzstd* -exec bash -c 'nm --defined-only {} 2>/dev/null | grep ZSTD_CCtxParams_setParameter && echo {}' \;
000000000001b268 T ZSTD_CCtxParams_setParameter
/usr/local/lib/libzstd.so.OLD
000000000001b268 T ZSTD_CCtxParams_setParameter
/usr/local/lib/libzstd.so.1.4.8
000000000001b268 T ZSTD_CCtxParams_setParameter
/usr/local/lib/libzstd.so.1
0000000000003890 T ZSTD_CCtxParams_setParameter
/usr/local/lib/libzstd.a

As you can see, i have renamed the libzstd.so to so.OLD in order to make the cmake configurator use the .a file which made breeze and openr work. BUT now i see that the symbol is indeed present in both the .a and .so files. So i am lost again..As i am sure that was not the case when i first checked. If that was the case from start, why would renaming the .so to .so.OLD fix my issue and make the projects relying on zstd work? 
All i can conclude is that this is a very peculiar issue with cmake build system sometimes using the system libzstd.1.3.8 and others 1.4.8 that broke the linking. Perhaps i missed something in the configuration phase of some of the dependencies projects build. But i will for sure spent some days banging my head why renaming the .so solved my problem in the first place. 
Thanks for your efforts, its my problem as it seems. Sorry for your time.

**Closed as completed** 2021-05-13 03:38 UTC
