### ISSUE TITLE
Add a ZSTD_defaultCLevel() function

### ISSUE THREAD

**Issue by ghost** [facebook/zstd#2531] opened 2021-03-11 05:00 UTC
The stable API has these two functions:
```c
int  ZSTD_minCLevel(void);  /*!< minimum negative compression level allowed */
int  ZSTD_maxCLevel(void);  /*!< maximum compression level available */
```
Does it need a `ZSTD_defaultCLevel()` function that returns the value of `ZSTD_CLEVEL_DEFAULT`?

**Comment by you-me227** [comment] 2021-03-16 04:57
> `
Duplicate of #`

**Comment by ghost** [comment] 2021-03-16 08:38
It can be used when dynamically linking to zstd.

This request is not strong, maybe very few people modify the value of `ZSTD_CLEVEL_DEFAULT`.

**Comment by terrelln** [comment] 2021-03-16 18:07
I think that very few people modify it, but since it is modifiable, and there is no other way to detect the default level, I wouldn't be against adding it.

**Comment by senhuang42** [comment] 2021-03-25 17:07
Included in #2555

**Closed as completed by senhuang42** 2021-03-25 17:07 UTC
Labels: feature request
