### ISSUE TITLE
The compilation order in the Makefile may be wrong

### ISSUE THREAD

**Issue by asarubbo** [facebook/zstd#419] opened 2016-10-14 07:35 UTC
From a compilation I get:

```
x86_64-pc-linux-gnu-clang-3.8: warning: -Wl,-O1: 'linker' input unused
x86_64-pc-linux-gnu-clang-3.8: warning: -Wl,--as-needed: 'linker' input unused
x86_64-pc-linux-gnu-clang-3.8: warning: -Wl,--hash-style=gnu: 'linker' input unused
x86_64-pc-linux-gnu-clang-3.8: warning: -Wl,-z,lazy: 'linker' input unused
```

I guess the right order should be
$CC $INCLUDE $CFLAGS $FILE.C -o $FILE.o $LDFLAGS

What do you think about?

**Comment by Cyan4973** [comment] 2016-10-14 17:02
How do you generate these warnings ?

**Comment by asarubbo** [comment] 2016-10-15 10:55
While I build it via portage (our package manager on gentoo) I have the way to add my ldflags.
clang warns about unused flags.

**Comment by Cyan4973** [comment] 2016-10-18 23:08
Latest update in "dev" branch uses implicit rules, which avoids described linker warnings in at least one place in the Makefile.
Let me know if it works better for you.

**Comment by Cyan4973** [comment] 2016-10-28 16:54
May I assume the problem is fixed in latest `dev` branch, and close the issue ?

**Comment by asarubbo** [comment] 2016-10-29 13:03
I'll retest on the next release

**Comment by asarubbo** [comment] 2016-11-02 14:53
I get the same with 1.1.1

**Comment by Cyan4973** [comment] 2016-11-02 21:14
Unfortunately, I've got troubles to properly test your use case.
When trying to use your suggested linker flag, for example `-Wl,-O1`, I get : 
```
ld: unknown option: -O1
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
which prevents completing the test...

**Closed** 2016-11-03 00:31 UTC

**Comment by Cyan4973** [comment] 2016-11-03 00:33
Found a working flag, and could properly test with it.

The issue wasn't a compilation order : in fact, to avoid the warning _no link flag_ must be present when no linking is performed.

The new build system in `dev` branch should avoid such side-effect.

**Comment by asarubbo** [comment] 2016-11-03 08:30
> The issue wasn't a compilation order : in fact, to avoid the warning no link flag must be present when no linking is performed.

I never talked about that. The linked flags in my case are added at link time.
