### ISSUE TITLE
1.3.8 tar file is broken

### ISSUE THREAD

**Issue by fenrus75** [facebook/zstd#1481] opened 2018-12-28 00:29 UTC
$ file zstd-1.3.8.tar.gz
zstd-1.3.8.tar.gz: gzip compressed data, from FAT filesystem (MS-DOS, OS/2, NT)

**Comment by fenrus75** [comment] 2018-12-28 00:33
seems it is double gzipd... the tar.gz got gzipped again

**Comment by lzutao** [comment] 2018-12-28 02:44
Confimed! cc @Cyan4973

**Comment by centminmod** [comment] 2018-12-28 04:52
seems to be fixed now

**Comment by Cyan4973** [comment] 2018-12-28 07:44
I'm not sure to understand what's the issue.
```
file zstd-1.3.8.tar.gz
zstd-1.3.8.tar.gz: gzip compressed data, from FAT filesystem (MS-DOS, OS/2, NT), original size 1862954             
file zstd-1.3.8.tar
zstd-1.3.8.tar: POSIX tar archive
```

I don't see any double-gzipping here.

These archives were produced by the same script which produced `v1.3.7` a few months ago.

**Comment by bket** [comment] 2018-12-28 08:54
I'm seeing the same issue as @fenrus75. On OpenBSD:

```
$ ftp https://github.com/facebook/zstd/releases/download/v1.3.8/zstd-1.3.8.tar.gz
$ file zstd-1.3.8.tar.gz                                                                                                                                    
zstd-1.3.8.tar.gz: gzip compressed data, from FAT filesystem (MS-DOS, OS/2, NT)
$ gunzip zstd-1.3.8.tar.gz                                                                                                                                  
$ file zstd-1.3.8.tar                                                                                                                                       
zstd-1.3.8.tar: gzip compressed data, was "zstd-1.3.8.tar", last modified: Thu Dec 27 18:44:03 2018, max compression, from Unix
```

**Comment by bket** [comment] 2018-12-28 09:51
For reference purposes:

```
$ ftp https://github.com/facebook/zstd/releases/download/v1.3.7/zstd-1.3.7.tar.gz 
$ file zstd-1.3.7.tar.gz                                                                                                                                    
zstd-1.3.7.tar.gz: gzip compressed data, was "zstd-1.3.7.tar", last modified: Fri Oct 19 21:39:11 2018, max compression, from Unix
```

**Comment by felixhandte** [comment] 2018-12-28 18:35
Ok, we're not sure what went wrong. But I was able to reproduce the issue.

We've replaced the `zstd-1.3.8.tar.gz` asset in the release. And I have tried round-tripping it and what I get back from GitHub now hash-matches `zstd-1.3.8.tar.gz.sha256` and unpacks correctly.

**Closed by felixhandte** 2018-12-28 18:35 UTC
