### ISSUE TITLE
Cross Compiling for Windows with CMake

### ISSUE THREAD

**Issue by Nemirtingas** [facebook/zstd#2142] opened 2020-05-15 10:53 UTC
**Describe the bug**
Duplicate flags are removed and they shouldn't.

**To Reproduce**
1. I use clang-cl toolchain from this git repository: https://github.com/ProdriveTechnologies/clang-msvc-sdk
2. Cross compile zstd
3. clang: error: cannot specify '/FoCMakeFiles/libzstd_static.dir/__/__/__/lib/common/entropy_common.c.obj' when compiling multiple source files
zstd-src/build/cmake/lib/CMakeFiles/libzstd_static.dir/build.make:86: recipe for target 'zstd-src/build/cmake/lib/CMakeFiles/libzstd_static.dir/__/__/__/lib/common/entropy_common.c.obj' failed

**Expected behavior**
I expected that it compiles.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 18.04 (docker)
 - Compiler clang, clang-cl, llvm
 - Build system CMake

**Additional context**
After investigating, it comes from this line in build/cmake/CMakeModules/AddZstdCompilationFlags.cmake:
```
...
# Remove duplicates compilation flags
    foreach (flag_var CMAKE_C_FLAGS CMAKE_C_FLAGS_DEBUG CMAKE_C_FLAGS_RELEASE
             CMAKE_C_FLAGS_MINSIZEREL CMAKE_C_FLAGS_RELWITHDEBINFO
             CMAKE_CXX_FLAGS CMAKE_CXX_FLAGS_DEBUG CMAKE_CXX_FLAGS_RELEASE
             CMAKE_CXX_FLAGS_MINSIZEREL CMAKE_CXX_FLAGS_RELWITHDEBINFO)
        if( ${flag_var} )
            separate_arguments(${flag_var})
--------->  list(REMOVE_DUPLICATES ${flag_var})
            string(REPLACE ";" " " ${flag_var} "${${flag_var}}")
            message(STATUS "${flag_var} ${${flag_var}}")
        endif()
    endforeach ()
...
```

It removes the duplicated -imsvc from the compile flags but it shouldn't.

**Comment by bimbashrestha** [comment] 2020-06-02 17:07
Thanks for posting the issue @Nemirtingas. Sorry for the late reply. I haven't reproduced this because building the linked toolchain looks a little time consuming.

Does simply conditioning the deduplication on ${flag_var} != -lmsvc fix the issue? If you could supply a PR for this, I'd be happy to help you get it merged!

**Comment by Nemirtingas** [comment] 2020-06-02 17:52
Hi,
Unfortunatly, its a bit more complex than that. Its not the variable that is duplicate, its whats inside of it:

```
Variable name (${flag_var}): CMAKE_C_FLAGS
Variable content (${${flag_var}}): -Xclang -fexceptions -Xclang -fcxx-exceptions -Xclang -D_CRT_SECURE_NO_WARNINGS --target=i686-windows-msvc -fms-compatibility-version=19.11 -Wno-unused-command-line-argument -imsvc /home/nemir/test_project/clang_windows_sdk/msvc/include -imsvc /home/nemir/test_project/clang_windows_sdk/winsdk/Include/10.0.18362.0/ucrt -imsvc /home/nemir/test_project/clang_windows_sdk/winsdk/Include/10.0.18362.0/shared -imsvc /home/nemir/test_project/clang_windows_sdk/winsdk/Include/10.0.18362.0/um -imsvc /home/nemir/test_project/clang_windows_sdk/winsdk/Include/10.0.18362.0/winrt -Xclang -ivfsoverlay -Xclang /home/nemir/test_project/extra/zstd/win32/winsdk_vfs_overlay.yaml -Wall -Wextra -Wundef -Wshadow -Wcast-align -Wcast-qual -Wstrict-prototypes```

The same would apply to the -Xclang flag. I fixed it temporarly by removing the duplicate removal code.

**Closed** 2020-06-16 00:41 UTC
Labels: build issue

**Comment by bimbashrestha** [comment] 2020-06-16 00:43
Just removed the de duplication logic. @Nemirtingas can you confirm that this resolves your issue?

**Comment by Nemirtingas** [comment] 2020-06-16 12:29
Hi,
Seems to be fine now.
Just compiled the dev branch without issues.
