### ISSUE TITLE
pip install issue on MacOS

### ISSUE THREAD

**Issue by Milkigit** [facebook/zstd#1986] opened 2020-02-03 20:34 UTC
Hi, I'm going to install zstd on MaxOS, but there are too many warnings, so installation failed.
I have no idea whether I am using some deprecated packages.

```
    zstd/lib/compress/zstd_compress_internal.h:335:17: error: use of undeclared identifier 'bounds'
        if (value > bounds.upperBound) return 0;
                    ^
    zstd/lib/compress/zstd_compress.c:67:50: error: use of undeclared identifier 'ZSTD_reset_parameters'
        {   size_t const err = ZSTD_CCtx_reset(cctx, ZSTD_reset_parameters);
                                                     ^
    zstd/lib/compress/zstd_compress.c:262:1: error: unknown type name 'ZSTD_bounds'
    ZSTD_bounds ZSTD_cParam_getBounds(ZSTD_cParameter param)
    ^
    zstd/lib/compress/zstd_compress.c:264:5: error: use of undeclared identifier 'ZSTD_bounds'; did you mean 'ZSTD_count'?
        ZSTD_bounds bounds = { 0, 0, 0 };
        ^~~~~~~~~~~
        ZSTD_count
    zstd/lib/compress/zstd_compress_internal.h:499:19: note: 'ZSTD_count' declared here
    MEM_STATIC size_t ZSTD_count(const BYTE* pIn, const BYTE* pMatch, const BYTE* const pInLimit)
                      ^
    zstd/lib/compress/zstd_compress.c:264:16: error: expected ';' after expression
        ZSTD_bounds bounds = { 0, 0, 0 };
                   ^
                   ;
    zstd/lib/compress/zstd_compress.c:264:17: error: use of undeclared identifier 'bounds'
        ZSTD_bounds bounds = { 0, 0, 0 };
                    ^
    zstd/lib/compress/zstd_compress.c:264:26: error: expected expression
        ZSTD_bounds bounds = { 0, 0, 0 };
                             ^
    zstd/lib/compress/zstd_compress.c:268:10: error: use of undeclared identifier 'ZSTD_c_compressionLevel'; did you mean 'ZSTD_p_compressionLevel'?
        case ZSTD_c_compressionLevel:
             ^~~~~~~~~~~~~~~~~~~~~~~
             ZSTD_p_compressionLevel
    /Users/min/.pyenv/versions/anaconda3-2019.03/include/zstd.h:1005:5: note: 'ZSTD_p_compressionLevel' declared here
        ZSTD_p_compressionLevel=100, /* Update all compression parameters according to pre-defined cLevel table
        ^
    zstd/lib/compress/zstd_compress.c:269:9: error: use of undeclared identifier 'bounds'
            bounds.lowerBound = ZSTD_minCLevel();
            ^
    zstd/lib/compress/zstd_compress.c:270:9: error: use of undeclared identifier 'bounds'
            bounds.upperBound = ZSTD_maxCLevel();
            ^
    zstd/lib/compress/zstd_compress.c:271:16: error: use of undeclared identifier 'bounds'
            return bounds;
                   ^
    zstd/lib/compress/zstd_compress.c:273:10: error: use of undeclared identifier 'ZSTD_c_windowLog'; did you mean 'ZSTD_p_windowLog'?
        case ZSTD_c_windowLog:
             ^~~~~~~~~~~~~~~~
             ZSTD_p_windowLog
    /Users/min/.pyenv/versions/anaconda3-2019.03/include/zstd.h:1011:5: note: 'ZSTD_p_windowLog' declared here
        ZSTD_p_windowLog,        /* Maximum allowed back-reference distance, expressed as power of 2.
        ^
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    20 errors generated.
    error: command 'gcc' failed with exit status 1
```

Thanks a lot!

**Comment by Cyan4973** [comment] 2020-02-03 20:58
Strange, as if the source was only partially updated ?

**Comment by bimbashrestha** [comment] 2020-02-04 18:59
It looks like there is already an issue for this filed under python-zstd. There seems to be some issues using anaconda or virtualenv? Is your pip installation in a virtual env? 

https://github.com/sergey-dryabzhinsky/python-zstd/issues/33

In any case, I believe the discussion of this topic should belong in the python-zstd repo and not here. Perhaps you could re-open the one there and we can close this one @Milkigit?

**Comment by bimbashrestha** [comment] 2020-02-05 18:41
Closing. We can reopen if it turns out there is an issue with zstd but right now it appears the issue is with python-zstd.

**Closed by bimbashrestha** 2020-02-05 18:41 UTC
Labels: Install issues
