### ISSUE TITLE
Resource leak

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [facebook/zstd#2091] opened 2020-04-27 03:28 UTC
Stream is opened
https://github.com/facebook/zstd/blob/16654625738d26ea8344eb4fb615bcbffd30b7f0/doc/educational_decoder/harness.c#L38
Opened file never closed
https://github.com/facebook/zstd/blob/16654625738d26ea8344eb4fb615bcbffd30b7f0/doc/educational_decoder/harness.c#L46

https://github.com/facebook/zstd/blob/16654625738d26ea8344eb4fb615bcbffd30b7f0/doc/educational_decoder/harness.c#L26

**Comment by brunoais** [comment] 2020-04-27 10:23
Why is it a leak? When the program exists, all resources are released by the OS.

If f was no longer pointing to the file by then, then it would be a leak. This way, the OS just closes the file when it's cleaning up after the process exits.

IMO, not a bug.

**Comment by Cyan4973** [comment] 2020-04-27 11:54
I agree with @brunoais here,
it's common practice that all resources are released on exiting a program.
A static analyzer should not count that event as a leak.

Also : `harness.c` is not part of `libzstd`, it's merely a test program.

**Comment by terrelln** [comment] 2020-04-28 18:56
I'm going to close this issue because:
1. These resources are freed at program exit.
2. This is in the educational decoder, which is not part of the zstd library or CLI, and shouldn't be used in production.

**Comment by terrelln** [comment] 2020-04-28 18:56
However, if you want to put up a PR to fix this, and it doesn't complicate the code, I would be happy to merge it.

**Closed by terrelln** 2020-04-28 18:56 UTC
