### ISSUE TITLE
zstd not buildable with PAC/BTI becauseof  `huf_decompress_amd64.S`

### ISSUE THREAD

**Issue by ggardet** [facebook/zstd#3841] opened 2023-11-30 14:12 UTC
**Describe the bug**
On aarch64/arm64, when we build with `-mbranch-protection=standard` to enable Pointer Authentication (PAC) and Branch Target Identification (BTI), the final link disable them, because huf_decompress_amd64.S does not support PAC and BTI.

The following warning message shows the issue:

```
[  139s] /usr/lib64/gcc/aarch64-suse-linux/13/../../../../aarch64-suse-linux/bin/ld: obj/conf_bc1626df636ebe4921decf3f88861d7a/huf_decompress_amd64.o: warning: BTI turned on by -z force-bti when all inputs do not have BTI in NOTE section.
```
This is a matter to add paciasp/autiasp in start/end of functions for PAC and BTI C (or hint #34) as landing pad on branches for BTI.

More information on :

PAC: https://developer.arm.com/documentation/102433/0100/Return-oriented-programming
BTI: https://developer.arm.com/documentation/102433/0100/Jump-oriented-programming

**To Reproduce**
1. Build with `-mbranch-protection=standard` and add `-z force-bti` to LD_FLAGS
2. See the warning message above

**Expected behavior**
zstd should build with PAC/BTI enabled just fine.

**Screenshots and charts**
N/A

**Desktop (please complete the following information):**
 - OS: openSUSE Tumbleweed aarch64
 - Version 1.5.5
 - Compiler gcc13
 - Flags `-mbranch-protection=standard -z force-bti`
 - Other relevant hardware specs aarch64
 - Build system Makefile

**Additional context**
N/A

**Comment by rossburton** [comment] 2023-11-30 17:38
Note that on **arm64** machines the `amd64.s` isn't useful, so zstd could either add the relevant section to mark the non-existent code as PAC/BTI, or only pull that file into builds where it is useful.

**Comment by terrelln** [comment] 2023-12-12 18:00
When building on arm64, this file is almost empty. It looks like it only contains this line:

https://github.com/facebook/zstd/blob/126ec2669c927b24acd38ea903a211c1b5416588/lib/decompress/huf_decompress_amd64.S#L17C38-L17C38

Is there a way to make `-mbranch-protection=standard` work with this?

**Comment by terrelln** [comment] 2023-12-12 18:04
Could we maybe manually add a note? We support Intel CET by including the header and annotating some functions.

**Comment by rossburton** [comment] 2023-12-13 12:55
Not pulling that file in for non-x86-64 builds seems like the best solution, but you could add a note to advertise that the (empty) section supports BTI. Something like this:

```
.pushsection .note.gnu.property, "a"
.balign 8
.long 4                 /* size of the name - "GNU\0" */
.long 0x10              /* size of descriptor */
.long 0x5               /* NT_GNU_PROPERTY_TYPE_0 */
.asciz "GNU"
.long 0xc0000000        /* pr_type - GNU_PROPERTY_AARCH64_FEATURE_1_AND */
.long 4                 /* pr_datasz - 4 bytes */
.long 1                 /* pr_data - GNU_PROPERTY_AARCH64_FEATURE_1_BTI */
.long 0                 /* pr_padding - bring everything to 8 byte alignment */
.popsection
```

**Comment by felixhandte** [comment] 2024-03-04 18:20
The reason we add the executable stack note unconditionally is because we found that people using alternate build systems from outside of the zstd project were including the assembly unconditionally. So this weighs in favor of including the note.

**Comment by terrelln** [comment] 2024-03-13 18:51
@rossburton @ggardet I believe that PR #3961 fixes the issue. I reproduced the warning in CI and this patch makes it go away, and looked at what the compilers & linux are doing. But I'm not an expert here, so please let me know if this is insufficient.

We will be making a release in the next few weeks, and this issue was deemed release blocking. PR #3961 will be included in this release.

**Closed as completed** 2024-03-13 20:15 UTC

**Comment by rossburton** [comment] 2024-03-13 21:43
That looks right to me, thanks.
