### ISSUE TITLE
Export "selected" CMake target for zstd

### ISSUE THREAD

**Issue by anthonyalayo** [facebook/zstd#3859] opened 2024-01-11 07:15 UTC
Can we have a consistent CMake library target exported?

For example with the curl project, if the standard CMake global variable `BUILD_SHARED_LIBS` is set, `LIB_SELECTED` will match accordingly: https://github.com/curl/curl/blob/master/CMakeLists.txt#L155-L159

```
# lib flavour selected for example and test programs.
if(BUILD_SHARED_LIBS)
  set(LIB_SELECTED ${LIB_SHARED})
else()
  set(LIB_SELECTED ${LIB_STATIC})
endif()
```

This is then used as an exported target (in addition to the fixed static/shared targets):
```
add_library(${LIB_NAME} ALIAS ${LIB_SELECTED})
add_library(${PROJECT_NAME}::${LIB_NAME} ALIAS ${LIB_SELECTED})
```

This makes pulling in curl quite clean. In comparison, I have to do the following when using `fetchcontent` with zstd:
```
set(ZSTD_LIBRARY libzstd_static)
if(BUILD_SHARED_LIBS)
  set(ZSTD_LIBRARY libzstd_shared)
endif()
```

**Comment by Cyan4973** [comment] 2024-03-04 04:19
Does the recently merged https://github.com/facebook/zstd/pull/3811 by @teo-tsirpanis answer this issue ?

**Comment by teo-tsirpanis** [comment] 2024-03-04 17:24
Curl exposes a unified target even if both static and shared libraries are built.

@Cyan4973 should we do the same here (and in lz4)? And if both are specified, should we prefer static or shared?

**Comment by anthonyalayo** [comment] 2024-03-04 17:41
If both are specified, we should rely on whatever `BUILD_SHARED_LIBS` is set to. This is a global CMake variable than can only be ON or OFF, and configures all subprojects.

**Comment by teo-tsirpanis** [comment] 2024-03-04 22:19
The problem is that zstd does not use `BUILD_SHARED_LIBS` at all. 🤔

**Comment by anthonyalayo** [comment] 2024-03-05 06:11
Even if it doesn't, that's what CMake uses, so it should work out well?

**Comment by terrelln** [comment] 2024-03-14 15:51
@anthonyalayo, @teo-tsirpanis please let me know if PR #3965 fixes your issues.

**Closed as completed** 2024-03-14 19:04 UTC

**Comment by anthonyalayo** [comment] 2024-03-14 19:27
Works, thanks!
