### ISSUE TITLE
http://www.zstd.net link in readme is broken

### ISSUE THREAD

**Issue by eudisd** [facebook/zstd#2074] opened 2020-04-07 05:44 UTC
**Describe the bug**

**To Reproduce**
1. Downloads data '...'
2. Run '...' with flags '...'
3. Scroll up on the log to '....'

**Expected behavior**

**Screenshots and charts**
If applicable, add screenshots and charts to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Mac]
 - Compiler [e.g gcc]
 - Flags [e.g O2]
 - Other relevant hardware specs [e.g. Dual-core]
 - Build system [e.g. Makefile]

**Additional context**

**Comment by bimbashrestha** [comment] 2020-04-07 05:49
Hi @eudisd, Thanks for submitting the issue. We are aware that zstd.net is down. This is a duplicate of https://github.com/facebook/zstd/issues/2070. So I'm going to close it.

**Closed by bimbashrestha** 2020-04-07 05:49 UTC
