### ISSUE TITLE
Packet corrupted - literal issue

### ISSUE THREAD

**Issue by shulib** [facebook/zstd#3325] opened 2022-11-30 15:49 UTC
Hi, 
I got a packet with literal section data: 62 80 01 04 10 88 1f 20 40
as you see:
literal header is 0x62 0x80 0x01 
header byte is 0x04 
a. size mode = 0 
b. literal compressed
c. Fse with table for weights 1 and 2
only one weight read (the even one) - weight 1 for symbol 0, I have 1 bit per weight.
why the tool corrupt this packet in literal section?
thanks,

**Comment by terrelln** [comment] 2022-12-20 00:25
@shulib how did you generate this literals section? What do you expect the decompressed literals to be?

The Huffman tree I read from the header is:
```
Symbol 0: weight 1
Symbol 1: weight 1
Symbol 2: weight 2
```

The bitstream contains 6 bits. I read 3 symbol 0s from the source, each one taking 2-bits. Then I run out of bits in the bitstream.

**Comment by terrelln** [comment] 2022-12-20 00:44
@shulib If there are `N` weights, only the first `N-1` should be encoded in the header (in this case with FSE). So in this case the header should only encode the weight of symbol 0. The weight of symbol 1 would be inferred, by the fact that the sum of the weights must be a power of 2.

It seems like upstream zstd did not generate this literals block. Because upstream zstd would have chosen to use the direct representation `huffman-header-byte >= 128` for both possible cases:

The table you expected:
```
symbol 0: weight 1
symbol 1: weight 1
```

Or the actual table:

```
symbol 0: weight 1
symbol 1: weight 1
symbol 2: weight 2
```

**Comment by terrelln** [comment] 2022-12-20 00:46
I'm going to close this issue, but if you have further questions please open a new issue & link to this one.

But if you open a new issue please include:
* How you generated the corrupted literals block
  * What tool generated it
  * What commit / version of that tool
  *  How would we reproduce the issue with that tool
  * Any other relevant information
* What you expected the decompressed data to be
* Any other relevant information

**Closed as completed by terrelln** 2022-12-20 00:46 UTC
